src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Experience_Type__c</fullName>
        <globalPicklist>Experience_Type</globalPicklist>
        <label>Experience Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Education_Level__c</fullName>
        <globalPicklist>Final_Level_of_Education</globalPicklist>
        <label>Final Education Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Position__c</fullName>
        <globalPicklist>Position</globalPicklist>
        <label>Last Position</label>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Candidate</fullName>
        <active>true</active>
        <label>Candidate</label>
    </recordTypes>
</CustomObject>

src/objects/Contact_Language__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Languages</relationshipLabel>
        <relationshipName>Contact_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Contact Languages</relationshipLabel>
        <relationshipName>Contact_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Language</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contact Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Sector__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Sectors</relationshipLabel>
        <relationshipName>Contact_Sectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Contact Sectors</relationshipLabel>
        <relationshipName>Contact_Sectors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Sector</label>
    <nameField>
        <displayFormat>CSI-{00000}</displayFormat>
        <label>Contact Sector Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Sectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Skills</relationshipLabel>
        <relationshipName>Contact_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Contact Skills</relationshipLabel>
        <relationshipName>Contact_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Skill</label>
    <nameField>
        <displayFormat>CSI-{00000}</displayFormat>
        <label>Contact Skill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Language__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Desired Languages</relationshipLabel>
        <relationshipName>Desired_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Languages</relationshipLabel>
        <relationshipName>Desired_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Language</label>
    <nameField>
        <displayFormat>DLI-{00000}</displayFormat>
        <label>Desired Language Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Sector__c.object
<CustomObject>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Sectors</relationshipLabel>
        <relationshipName>Desired_Sectors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Desired Sectors</relationshipLabel>
        <relationshipName>Desired_Sectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Sector</label>
    <nameField>
        <displayFormat>DSI-{00000}</displayFormat>
        <label>Desired Sector Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Sectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Skills</relationshipLabel>
        <relationshipName>Desired_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Desired Skills</relationshipLabel>
        <relationshipName>Desired_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Skill</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Desired Skill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education_Scores__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Education Scores</label>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Position_Scores__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Position Scores</label>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Experience_Type__c</fullName>
        <globalPicklist>Experience_Type</globalPicklist>
        <label>Experience Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Education_Level__c</fullName>
        <globalPicklist>Final_Level_of_Education</globalPicklist>
        <label>Final Education Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_Required__c</fullName>
        <globalPicklist>Position</globalPicklist>
        <label>Level Required</label>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Score_Table__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Language_Cap__c</fullName>
        <label>Language Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language_Match__c</fullName>
        <label>Language Match</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Education_Score__c</fullName>
        <label>Max Education Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Position_Score__c</fullName>
        <label>Max Position Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Public_Private_Match__c</fullName>
        <label>Public Private Match</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_Per_Education_Level__c</fullName>
        <label>Score Per Education Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_Per_Position_Level__c</fullName>
        <label>Score Per Position Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sector_Cap__c</fullName>
        <label>Sector Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sector_Match__c</fullName>
        <label>Sector Match</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_Cap__c</fullName>
        <label>Skill Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_Match__c</fullName>
        <label>Skill Match</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Table</label>
</CustomObject>

src/objects/Sector__c.object
<CustomObject>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScoringEngine.cls
public class ScoringEngine {
    public static Decimal totalScore(Requirement__c requirement) {
        
        Decimal totalScore = 0;
        Decimal publicPrivateMatchSetting = Score_Table__c.getOrgDefaults().Public_Private_Match__c;
        
        Decimal sectorCapSetting = Score_Table__c.getOrgDefaults().Sector_Cap__c;
        Decimal sectorMatchSetting = Score_Table__c.getOrgDefaults().Sector_Match__c;
        
        Decimal skillCapSetting = Score_Table__c.getOrgDefaults().Skill_Cap__c;
        Decimal skillMatchSetting = Score_Table__c.getOrgDefaults().Skill_Match__c;
        
        Decimal languageCapSetting = Score_Table__c.getOrgDefaults().Language_Cap__c;
        Decimal languageMatchSetting = Score_Table__c.getOrgDefaults().Language_Match__c;
        
        Decimal educationBaseScore = Score_Table__c.getOrgDefaults().Score_Per_Education_Level__c;
        Decimal maxEducationScore = Score_Table__c.getOrgDefaults().Max_Education_Score__c;
        Education_Scores__c educationScoreRequirement = 
            requirement.Final_Education_Level__c != null ? Education_Scores__c.getValues(requirement.Final_Education_Level__c) : null;
        
        Decimal positionBaseScore = Score_Table__c.getOrgDefaults().Score_Per_Position_Level__c;
        Decimal maxPositionScore = Score_Table__c.getOrgDefaults().Max_Position_Score__c;
        Position_Scores__c positionScoreRequirement = 
            requirement.Level_Required__c != null ? Position_Scores__c.getValues(requirement.Level_Required__c) : null;
        
        totalScore += publicPrivateMatchSetting != null ? publicPrivateMatchSetting : 0;
        
        if (sectorCapSetting != null && sectorMatchSetting != null) {
        	totalScore += (requirement.Desired_Sectors__r.size() * sectorMatchSetting) > sectorCapSetting ? sectorCapSetting : (requirement.Desired_Sectors__r.size() * sectorMatchSetting);    
        }
        
        if (skillCapSetting != null && skillMatchSetting != null) {
        	totalScore += (requirement.Desired_Skills__r.size() * skillMatchSetting) > skillCapSetting ? skillCapSetting : (requirement.Desired_Skills__r.size() * skillMatchSetting);    
        }
        
        if (languageCapSetting != null && languageMatchSetting != null) {
        	totalScore += (requirement.Desired_Languages__r.size() * languageMatchSetting) > languageCapSetting ? languageCapSetting : (requirement.Desired_Languages__r.size() * languageMatchSetting);    
        }
        
        if (educationScoreRequirement != null && educationBaseScore != null && maxEducationScore != null) {
            if (educationScoreRequirement.Score__c != null) {
                Decimal maxPossibleScore = ((maxEducationScore - educationScoreRequirement.Score__c) + 1) * educationBaseScore;
				totalScore += maxPossibleScore > 0 ? maxPossibleScore : 0;            
            }
        }
        
        if (positionScoreRequirement != null && positionBaseScore != null && maxPositionScore != null) {
            if (positionScoreRequirement.Score__c != null) {
                Decimal maxPossibleScore = ((maxPositionScore - positionScoreRequirement.Score__c) + 1) * positionBaseScore;
				totalScore += maxPossibleScore > 0 ? maxPossibleScore : 0;            
            }
        }
        
        return totalScore;
    }
    
	public static Decimal score(Requirement__c requirement, Contact candidate) {
        
        return 
            publicPrivateMatch(requirement, candidate) +
            sectorMatch(requirement, candidate) +
            skillMatch(requirement, candidate) +
            languageMatch(requirement, candidate) +
            educationLevelMatch(requirement, candidate) +
            positionLevelMatch(requirement, candidate);
    }
    
    public static Decimal publicPrivateMatch(Requirement__c requirement, Contact candidate) {
        System.debug('******In publicPrivateMatch Match');
        
        if (requirement.Experience_Type__c != null) {
        	if (requirement.Experience_Type__c == 'Both' || candidate.Experience_Type__c == 'Both') {
            	return Score_Table__c.getOrgDefaults().Public_Private_Match__c;
            } else if (requirement.Experience_Type__c == candidate.Experience_Type__c) {
                return Score_Table__c.getOrgDefaults().Public_Private_Match__c;
            } else {
                return 0;
            }    
        } else {
            return 0;
        }
    }
    
    public static Decimal sectorMatch(Requirement__c requirement, Contact candidate) {
        
        System.debug('******In Sector Match');
        Decimal score = 0;
        
        if (requirement.Desired_Sectors__r.size() > 0 && candidate.Contact_Sectors__r.size() > 0) {
            for (Desired_Sector__c desiredSector : requirement.Desired_Sectors__r) {
                for (Contact_Sector__c contactSector : candidate.Contact_Sectors__r) {
                    if (desiredSector.Sector__c == contactSector.Sector__c) {
                        score += Score_Table__c.getOrgDefaults().Sector_Match__c;
                    }
                }
            }
        } 
        
        if (Score_Table__c.getOrgDefaults().Sector_Cap__c != null) {
            if (score > Score_Table__c.getOrgDefaults().Sector_Cap__c) {
                return Score_Table__c.getOrgDefaults().Sector_Cap__c;
            } else {
                return score;
            }
        } else {
        	return score;    
        }
    }
    
    public static Decimal skillMatch(Requirement__c requirement, Contact candidate) {
        
        System.debug('******In Skills Match');
        Decimal score = 0;
        
        if (requirement.Desired_Skills__r.size() > 0 && candidate.Contact_Skills__r.size() > 0) {
            for (Desired_Skill__c desiredSkill : requirement.Desired_Skills__r) {
                for (Contact_Skill__c contactSkill : candidate.Contact_Skills__r) {
                    if (desiredSkill.Skill__c == contactSkill.Skill__c) {
                        score += Score_Table__c.getOrgDefaults().Skill_Match__c;
                    }
                }
            }
        } 
        
        if (Score_Table__c.getOrgDefaults().Skill_Cap__c != null) {
            if (score > Score_Table__c.getOrgDefaults().Skill_Cap__c) {
                return Score_Table__c.getOrgDefaults().Skill_Cap__c;
            } else {
                return score;
            }
        } else {
        	return score;    
        }
    }
    
    public static Decimal languageMatch(Requirement__c requirement, Contact candidate) {
        
        System.debug('******In Language Match');
        Decimal score = 0;
        
        if (requirement.Desired_Languages__r.size() > 0 && candidate.Contact_Languages__r.size() > 0) {
            for (Desired_Language__c desiredLanguage : requirement.Desired_Languages__r) {
                for (Contact_Language__c contactLanguage : candidate.Contact_Languages__r) {
                    if (desiredLanguage.Language__c == contactLanguage.Language__c) {
                        score += Score_Table__c.getOrgDefaults().Language_Match__c;
                    }
                }
            }
        } 
        
        if (Score_Table__c.getOrgDefaults().Language_Cap__c != null) {
            if (score > Score_Table__c.getOrgDefaults().Language_Cap__c) {
                return Score_Table__c.getOrgDefaults().Language_Cap__c;
            } else {
                return score;
            }
        } else {
        	return score;    
        }
    }
    
    public static Decimal educationLevelMatch(Requirement__c requirement, Contact candidate) {
        
        Decimal baseScore = Score_Table__c.getOrgDefaults().Score_Per_Education_Level__c;
        
        if (baseScore != null) {
            if (requirement.Final_Education_Level__c != null && candidate.Final_Education_Level__c != null) {
                Education_Scores__c educationScoreRequirement = Education_Scores__c.getValues(requirement.Final_Education_Level__c);
                Education_Scores__c educationScoreCandidate = Education_Scores__c.getValues(candidate.Final_Education_Level__c);
                
                if (educationScoreRequirement != null && educationScoreCandidate != null) {
                    Decimal score = ((educationScoreCandidate.Score__c - educationScoreRequirement.Score__c) + 1) * baseScore;
                    return score < 0 ? 0 : score;    
                } else {
                    return 0;
                }
                
            } else {
                return 0;
            }
        } else {
            return 0;
        }
    }
    
    public static Decimal positionLevelMatch(Requirement__c requirement, Contact candidate) {
        
        Decimal baseScore = Score_Table__c.getOrgDefaults().Score_Per_Position_Level__c;
        
        if (baseScore != null) {
            if (requirement.Level_Required__c != null && candidate.Last_Position__c != null) {
                Position_Scores__c positionScoreRequirement = Position_Scores__c.getValues(requirement.Level_Required__c);
                Position_Scores__c positionScoreCandidate = Position_Scores__c.getValues(candidate.Last_Position__c);
                
                if (positionScoreRequirement != null && positionScoreCandidate != null) {
                    Decimal score = ((positionScoreCandidate.Score__c - positionScoreRequirement.Score__c) + 1) * baseScore;
                    return score < 0 ? 0 : score;    
                } else {
                    return 0;
                }
                
            } else {
                return 0;
            }
        } else {
            return 0;
        }
    }
}