src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Eligible_to_Work_in_the_UK__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible to Work in the UK</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Experience_Type__c</fullName>
        <globalPicklist>Experience_Type</globalPicklist>
        <label>Experience Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Education_Level__c</fullName>
        <globalPicklist>Final_Level_of_Education</globalPicklist>
        <label>Final Education Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Position__c</fullName>
        <globalPicklist>Position</globalPicklist>
        <label>Last Position</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Travel_Distance__c</fullName>
        <label>Max Travel Distance</label>
        <picklist>
            <picklistValues>
                <fullName>Over 25 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Up to 25 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No more than 10 miles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under 5 miles</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Profile_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Profile Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Frequency_Type_Monthly__c</fullName>
        <globalPicklist>Work_Frequency_Type_Monthly</globalPicklist>
        <label>Work Frequency Type - Monthly</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Frequency_Type_Weekly__c</fullName>
        <globalPicklist>Work_Frequency_Type_Weekly</globalPicklist>
        <label>Work Frequency Type - Weekly</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_from_home__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work from home?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Candidate</fullName>
        <active>true</active>
        <label>Candidate</label>
    </recordTypes>
</CustomObject>

src/objects/Contact_Language__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Languages</relationshipLabel>
        <relationshipName>Contact_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Contact Languages</relationshipLabel>
        <relationshipName>Contact_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Language</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Contact Language Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Sector__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Sectors</relationshipLabel>
        <relationshipName>Contact_Sectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Contact Sectors</relationshipLabel>
        <relationshipName>Contact_Sectors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Sector</label>
    <nameField>
        <displayFormat>CSI-{00000}</displayFormat>
        <label>Contact Sector Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Sectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Skills</relationshipLabel>
        <relationshipName>Contact_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Contact Skills</relationshipLabel>
        <relationshipName>Contact_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Skill</label>
    <nameField>
        <displayFormat>CSI-{00000}</displayFormat>
        <label>Contact Skill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Language__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Desired Languages</relationshipLabel>
        <relationshipName>Desired_Languages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Languages</relationshipLabel>
        <relationshipName>Desired_Languages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Language</label>
    <nameField>
        <displayFormat>DLI-{00000}</displayFormat>
        <label>Desired Language Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Languages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Sector__c.object
<CustomObject>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Sectors</relationshipLabel>
        <relationshipName>Desired_Sectors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <referenceTo>Sector__c</referenceTo>
        <relationshipLabel>Desired Sectors</relationshipLabel>
        <relationshipName>Desired_Sectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Sector</label>
    <nameField>
        <displayFormat>DSI-{00000}</displayFormat>
        <label>Desired Sector Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Sectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Desired_Skill__c.object
<CustomObject>
    <fields>
        <fullName>Requirement__c</fullName>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Desired Skills</relationshipLabel>
        <relationshipName>Desired_Skills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Desired Skills</relationshipLabel>
        <relationshipName>Desired_Skills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Desired Skill</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Desired Skill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desired Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Match__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requirement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requirement</label>
        <referenceTo>Requirement__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Match Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Experience_Type__c</fullName>
        <globalPicklist>Experience_Type</globalPicklist>
        <label>Experience Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Education_Level__c</fullName>
        <globalPicklist>Final_Level_of_Education</globalPicklist>
        <label>Final Education Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Laptop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Laptop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Level_Required__c</fullName>
        <globalPicklist>Position</globalPicklist>
        <label>Level Required</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Frequency_Type_Monthly__c</fullName>
        <globalPicklist>Work_Frequency_Type_Monthly</globalPicklist>
        <label>Work Frequency Type - Monthly</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Frequency_Type_Weekly__c</fullName>
        <globalPicklist>Work_Frequency_Type_Weekly</globalPicklist>
        <label>Work Frequency Type - Weekly</label>
        <type>Picklist</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sector__c.object
<CustomObject>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MatchingEngine.cls
public class MatchingEngine implements Queueable {
    
    List<Id> recordIds;
    Boolean candidateMode;
    
    public String contactQuery() {
        String result = '';
        result += 'SELECT ';
        result += '   Id, ';
        result += '   Name, 	';
        result += '   Experience_Type__c, ';
        result += '   Final_Education_Level__c, ';
        result += '   Last_Position__c, ';
        result += '   Max_Travel_Distance__c, ';
        result += '   (Select Id, Name, Skill__c, Skill__r.Name From Contact_Skills__r), ';
        result += '   (Select Id, Name, Language__c, Language__r.Name FROM Contact_Languages__r), ';
        result += '   (Select Id, Name, Sector__c, Sector__r.Name From Contact_Sectors__r),';
        result += '   Work_Frequency_Type_Monthly__c,';
        result += '   Work_Frequency_Type_Weekly__c,';
        result += '   Work_from_home__c';
        result += ' FROM ';
        result += '   CONTACT '; 
        result += ' WHERE '; 
        result += '     Profile_Complete__c = true';
        result += ' AND Eligible_to_Work_in_the_UK__c = true';
        
        if (candidateMode) {
            result += ' AND Id IN (\'' + String.join(recordIds, '\',\'') + '\')';
        }
        return result;
    }
    
    public String requirementQuery() {
        String result = '';
        result += 'SELECT'; 
        result += '  Id,'; 
        result += '  Experience_Type__c,'; 	
        result += '  Final_Education_Level__c,'; 
        result += '  Laptop__c,'; 
        result += '  Level_Required__c,';
        result += '  (Select Id, Name, Skill__c, Skill__r.Name From Desired_Skills__r),'; 
        result += '  (Select Id, Name, Language__c, Language__r.Name FROM Desired_Languages__r),'; 
        result += '  (Select Id, Name, Sector__c, Sector__r.Name From Desired_Sectors__r),';
        result += '  Work_Frequency_Type_Monthly__c,';
        result += '  Work_Frequency_Type_Weekly__c';
        result += ' FROM '; 
        result += '    Requirement__c'; 
        result += ' WHERE '; 
        result += '    Completed__c = true';
            
        if (!candidateMode) {
            result += ' AND Id IN (\'' + String.join(recordIds, '\',\'') + '\')';
        }
        
        return result;
    }
    
    public MatchingEngine(List<Id> recordIds, Boolean candidateMode) {
    	this.candidateMode = candidateMode;
        this.recordIds = recordIds;
    }
    
    public void execute(QueueableContext context) {
        
        List<Contact> contacts = (List<Contact>) Database.query(contactQuery());
        List<Requirement__c> requirements = (List<Requirement__c>) Database.query(requirementQuery());
        
        // Iterate and create records
        List<Match__c> matches = new List<Match__c>();
        for (Requirement__c requirement : requirements) {
            
            Decimal totalScore = ScoringEngine.totalScore(requirement);
            
            if (totalScore > 0) {
            	for (Contact candidate : contacts) {
                    matches.add(
                        new Match__c(
                            Requirement__c = requirement.Id, 
                            Contact__c = candidate.Id, 
                            Score__c = (ScoringEngine.score(requirement, candidate) / totalScore) * 100,
                            External_Id__c = requirement.Id + '|' + candidate.Id
                        )
                    );
                }    
            }
        }
        
        // Insert records
        upsert matches Match__c.External_Id__c;
    }
}