src/objects/Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Requirement</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RequirementTriggerHandler.cls
public class RequirementTriggerHandler {
	public static void beforeInsert(List<Requirement__c> newList, Map<Id, Requirement__c> newMap) {}
    public static void afterInsert(List<Requirement__c> newList, Map<Id, Requirement__c> newMap) {
        // Start Job
        startMatching(newList, new Map<Id,Requirement__c>());
    }
    
    public static void beforeUpdate(List<Requirement__c> oldList, Map<Id, Requirement__c> oldMap, List<Requirement__c> newList, Map<Id, Requirement__c> newMap) {}
    
    public static void afterUpdate(List<Requirement__c> oldList, Map<Id, Requirement__c> oldMap, List<Requirement__c> newList, Map<Id, Requirement__c> newMap) {
        // Start Job
        startMatching(newList, oldMap);
    }
    
    public static void startMatching(List<Requirement__c> requirements, Map<Id, Requirement__c> oldMap) {
        List<Id> reqIdsToStartJobFor = new List<Id>();
        for (Requirement__c req : requirements) {
            if (req.Completed__c) {
                if (oldMap.containsKey(req.Id)) {
                    if(!oldMap.get(req.Id).Completed__c) {
                        reqIdsToStartJobFor.add(req.Id);
                    }    
                } else {
                    reqIdsToStartJobFor.add(req.Id);
                } 
            }
        }
        
        if (reqIdsToStartJobFor.size() > 0) {
            System.enqueueJob(new MatchingEngine(reqIdsToStartJobFor, false));
        }
    }
}